/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkOrdersRouteImport } from './routes/work-orders'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MaterialsRouteImport } from './routes/materials'
import { Route as ItemsRouteImport } from './routes/items'
import { Route as IpcsRouteImport } from './routes/ipcs'
import { Route as InspectionRequestsRouteImport } from './routes/inspection-requests'
import { Route as BidsRouteImport } from './routes/bids'
import { Route as BidProposalsRouteImport } from './routes/bid-proposals'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as IndexRouteImport } from './routes/index'

const WorkOrdersRoute = WorkOrdersRouteImport.update({
  id: '/work-orders',
  path: '/work-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MaterialsRoute = MaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemsRoute = ItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRouteImport,
} as any)
const IpcsRoute = IpcsRouteImport.update({
  id: '/ipcs',
  path: '/ipcs',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionRequestsRoute = InspectionRequestsRouteImport.update({
  id: '/inspection-requests',
  path: '/inspection-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const BidsRoute = BidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => rootRouteImport,
} as any)
const BidProposalsRoute = BidProposalsRouteImport.update({
  id: '/bid-proposals',
  path: '/bid-proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/bid-proposals': typeof BidProposalsRoute
  '/bids': typeof BidsRoute
  '/inspection-requests': typeof InspectionRequestsRoute
  '/ipcs': typeof IpcsRoute
  '/items': typeof ItemsRoute
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/bid-proposals': typeof BidProposalsRoute
  '/bids': typeof BidsRoute
  '/inspection-requests': typeof InspectionRequestsRoute
  '/ipcs': typeof IpcsRoute
  '/items': typeof ItemsRoute
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/bid-proposals': typeof BidProposalsRoute
  '/bids': typeof BidsRoute
  '/inspection-requests': typeof InspectionRequestsRoute
  '/ipcs': typeof IpcsRoute
  '/items': typeof ItemsRoute
  '/materials': typeof MaterialsRoute
  '/projects': typeof ProjectsRoute
  '/work-orders': typeof WorkOrdersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/bid-proposals'
    | '/bids'
    | '/inspection-requests'
    | '/ipcs'
    | '/items'
    | '/materials'
    | '/projects'
    | '/work-orders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/bid-proposals'
    | '/bids'
    | '/inspection-requests'
    | '/ipcs'
    | '/items'
    | '/materials'
    | '/projects'
    | '/work-orders'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/bid-proposals'
    | '/bids'
    | '/inspection-requests'
    | '/ipcs'
    | '/items'
    | '/materials'
    | '/projects'
    | '/work-orders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  BidProposalsRoute: typeof BidProposalsRoute
  BidsRoute: typeof BidsRoute
  InspectionRequestsRoute: typeof InspectionRequestsRoute
  IpcsRoute: typeof IpcsRoute
  ItemsRoute: typeof ItemsRoute
  MaterialsRoute: typeof MaterialsRoute
  ProjectsRoute: typeof ProjectsRoute
  WorkOrdersRoute: typeof WorkOrdersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-orders': {
      id: '/work-orders'
      path: '/work-orders'
      fullPath: '/work-orders'
      preLoaderRoute: typeof WorkOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/materials': {
      id: '/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof MaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ipcs': {
      id: '/ipcs'
      path: '/ipcs'
      fullPath: '/ipcs'
      preLoaderRoute: typeof IpcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspection-requests': {
      id: '/inspection-requests'
      path: '/inspection-requests'
      fullPath: '/inspection-requests'
      preLoaderRoute: typeof InspectionRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bids': {
      id: '/bids'
      path: '/bids'
      fullPath: '/bids'
      preLoaderRoute: typeof BidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bid-proposals': {
      id: '/bid-proposals'
      path: '/bid-proposals'
      fullPath: '/bid-proposals'
      preLoaderRoute: typeof BidProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  BidProposalsRoute: BidProposalsRoute,
  BidsRoute: BidsRoute,
  InspectionRequestsRoute: InspectionRequestsRoute,
  IpcsRoute: IpcsRoute,
  ItemsRoute: ItemsRoute,
  MaterialsRoute: MaterialsRoute,
  ProjectsRoute: ProjectsRoute,
  WorkOrdersRoute: WorkOrdersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
